x-uffizzi:
  ingress:
    service: app
    port: 3000
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      volumes:
        - ./:/app
    environment:
      NODE_ENV: staging
      NEXT_PUBLIC_LOGFLARE_API_KEY: ${NEXT_PUBLIC_LOGFLARE_API_KEY}
      NEXT_PUBLIC_LOGFLARE_SOURCE_ID: ${NEXT_PUBLIC_LOGFLARE_SOURCE_ID}
      VERCEL_GIT_COMMIT_SHA: ${VERCEL_GIT_COMMIT_SHA}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}
      SENTRY_PROJECT: ${SENTRY_PROJECT}
      SENTRY_ORG: ${SENTRY_ORG}
      NEXT_PUBLIC_SENTRY_ENV: ${NEXT_PUBLIC_SENTRY_ENV}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_VERCEL_URL: ${UFFIZZI_URL}
    deploy:
      resources:
        limits:
          memory: 250M


secrets:
  NEXT_PUBLIC_LOGFLARE_API_KEY:
    external: true
    name: "NEXT_PUBLIC_LOGFLARE_API_KEY"
  NEXT_PUBLIC_LOGFLARE_SOURCE_ID:
    external: true
    name: "NEXT_PUBLIC_LOGFLARE_SOURCE_ID"
  VERCEL_GIT_COMMIT_SHA:
    external: true
    name: "VERCEL_GIT_COMMIT_SHA"
  SENTRY_AUTH_TOKEN:
    external: true
    name: "SENTRY_AUTH_TOKEN"
  NEXT_PUBLIC_SENTRY_DSN:
    external: true
    name: "NEXT_PUBLIC_SENTRY_DSN"
  SENTRY_PROJECT:
    external: true
    name: "SENTRY_PROJECT"
  SENTRY_ORG:
    external: true
    name: "SENTRY_ORG"
  NEXT_PUBLIC_SENTRY_ENV:
    external: true
    name: "NEXT_PUBLIC_SENTRY_ENV"
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    external: true
    name: "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  NEXT_PUBLIC_SUPABASE_URL:
    external: true
    name: "NEXT_PUBLIC_SUPABASE_URL"
    
  