on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
    secrets:
      NEXT_PUBLIC_LOGFLARE_API_KEY:
        required: true
      NEXT_PUBLIC_LOGFLARE_SOURCE_ID:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    env:
      NEXT_PUBLIC_LOGFLARE_API_KEY: ${{ secrets.NEXT_PUBLIC_LOGFLARE_API_KEY }}
      NEXT_PUBLIC_LOGFLARE_SOURCE_ID: ${{ secrets.NEXT_PUBLIC_LOGFLARE_SOURCE_ID }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: initist
          SENTRY_PROJECT: initist
        with:
          environment: ${{ inputs.deploy_env }}
          sourcemaps: './.next'
