name: Release

on:
  push:
    branches:
      - development
      - main

jobs:
  staging_release:
    if: ${{ github.ref_name == 'development' }}
    uses: ./.github/workflows/base-release.yml
    with:
      env: staging
  production_release:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/base-release.yml
    with:
      env: production
